spring.application.name=backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/knowledgecanvas
spring.datasource.username=knowledgecanvas_user
spring.datasource.password=RadhaKrishn
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true